In [8]:
%load_ext autoreload
%autoreload 2

import os,sys,warnings
import h5py, pandas
import numpy as np
np.seterr(invalid=['ignore','warn'][0])
np.set_printoptions(legacy='1.25')
import math,cmath,pickle
from matplotlib.backends.backend_pdf import PdfPages
from scipy.optimize import curve_fit
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.style.use('default')
mpl.rcParams['figure.facecolor'] = 'white'
mpl.rcParams['figure.titlesize'] = 20
mpl.rcParams['figure.figsize'] = [6.4*1.2,4.8*1.2]
mpl.rcParams['axes.labelsize'] = 30
mpl.rcParams['axes.titlesize'] = 30
mpl.rcParams['lines.marker'] = 's'
mpl.rcParams['lines.linestyle'] = ''
mpl.rcParams['lines.markersize'] = 8
mpl.rcParams['errorbar.capsize'] = 12
mpl.rcParams['xtick.labelsize'] = mpl.rcParams['ytick.labelsize'] = 22
mpl.rcParams['xtick.major.size'] = mpl.rcParams['ytick.major.size'] = 10
mpl.rcParams['xtick.top']=mpl.rcParams['ytick.right']=True
mpl.rcParams['xtick.direction']=mpl.rcParams['ytick.direction']='in'
mpl.rcParams['legend.fontsize'] = 24
plt.rcParams["font.family"] = "serif"
plt.rcParams["mathtext.fontset"] = "dejavuserif"

# mpl.rcParams.update({"axes.grid" : True})
import util as yu
yu.flag_fast=False

hbarc = 1/197.327

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [18]:
lats=['BMW','MILC','Polarizability','B64']
lat_Ts=np.array([5.6,8.4,9.2,10.2])
lat_Ls=np.array([5.6,5.6,4.6,5.1])
dEs=np.array([2,2,4,3])
mpi=140
for t in [1.0,1.5]:
    t1=2*mpi/dEs; t2=np.exp(-mpi*(lat_Ts-2*t)*hbarc)
    print(t)
    print(t1,t2)
    print(t1*t2)
    print()

1.0
[140.         140.          70.          93.33333333] [0.07775938 0.01066608 0.00604652 0.00297428]
[10.8863139   1.49325179  0.42325654  0.27759919]

1.5
[140.         140.          70.          93.33333333] [0.15808004 0.02168349 0.01229221 0.00604652]
[22.13120547  3.03568889  0.86045446  0.56434205]

