In [1]:
# cyclone
# cfgs_all_j

import os
import h5py
import numpy as np

ens='cB211.072.64'

cfg2old=lambda cfg: cfg[1:]+'_r'+{'a':'0','b':'1','c':'2','d':'3'}[cfg[0]]
cfg2new=lambda cfg: {'0':'a','1':'b','2':'c','3':'d'}[cfg[-1]] + cfg[:4]

path=f'/nvme/h/cy22yl1/projectData/02_discNJN_1D/{ens}/data_pre_j/'
cfgs=[cfg2new(cfg) for cfg in os.listdir(path)]; cfgs.sort()

with open('data_aux/cfgs_all_j','w') as f:
    f.write('\n'.join(cfgs))

In [ ]:
# cyclone
# cfgs_all_jg

import os
import h5py
import numpy as np

ens='cB211.072.64'
basePath='/onyx/qdata/gspanoudes/Local_operators/Matrix_elements/cB64/data/gluon_loops_stout4D/'
stouts=range(40+1)
replicas=['cB64a','cB64b']; labels=['a','b']

replica2label={replica:label for replica,label in zip(replicas,labels)}
label2replica={label:replica for replica,label in zip(replicas,labels)}
cfg2old=lambda cfg: cfg[1:]+'_r'+{'a':'0','b':'1','c':'2','d':'3'}[cfg[0]]
cfg2new=lambda cfg: {'0':'a','1':'b','2':'c','3':'d'}[cfg[-1]] + cfg[:4]

cfgs=[replica2label[replica]+cfg for replica in replicas for cfg in os.listdir(f'{basePath}stout{0}/{replica}')]
cfgs.sort()

cfg=cfgs[0]
path=f'{basePath}stout{0}/{label2replica[cfg[0]]}/{cfg[1:]}/'
sizes=[os.path.getsize(f'{path}{file}') for file in os.listdir(path)]

cfgsDic={}
for stout in stouts:
    print(stout,end='         \r')
    t=[replica2label[replica]+cfg for replica in replicas for cfg in os.listdir(f'{basePath}stout{stout}/{replica}')]
    t.sort()
    assert(np.all(cfgs==t))
    for cfg in cfgs:
        path=f'{basePath}stout{stout}/{label2replica[cfg[0]]}/{cfg[1:]}/'
        t=[os.path.getsize(f'{path}{file}') for file in os.listdir(path)]
        assert(np.all(sizes==t))

with open('data_aux/cfgs_all_jg','w') as f:
    f.write('\n'.join(cfgs))

In [34]:
# cfgs_all_N
# NsrcDic

import os,pickle
import h5py
import numpy as np

ens='cB211.072.64'

cfg2old=lambda cfg: cfg[1:]+'_r'+{'a':'0','b':'1','c':'2','d':'3'}[cfg[0]]
cfg2new=lambda cfg: {'0':'a','1':'b','2':'c','3':'d'}[cfg[-1]] + cfg[:4]

path=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/{ens}/data_pre_N'
cfgs=[cfg2new(cfg) for cfg in os.listdir(path)]; cfgs.sort()

with open('data_aux/cfgs_all_N','w') as f:
    f.write('\n'.join(cfgs))
cfgs_all_N=cfgs

basepath=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/{ens}/data_post_hold/'

# files=['N.h5_hch02k_twop','N.h5_twop_threep_2','N.h5_twop_threep_dt20_64srcs']
# NsrcDic={}
# for i,cfg in enumerate(cfgs_all_N):
#     print(i+1,len(cfgs_all_N),end='               \r')
#     t=[]
#     for file in files:
#         path=f'{basepath}{cfg}/{file}'
#         if not os.path.exists(path):
#             # NsrcDic[(cfg,file)]=0
#             t.append(0)
#             continue
#         with h5py.File(path) as f:
#             Nsrc=len(f['data'].keys())
#             # NsrcDic[(cfg,file)]=Nsrc
#             t.append(Nsrc)
#     NsrcDic[cfg]=tuple(t)
#     # break

# with open('data_aux/NsrcDic.pkl','wb') as f:
#     pickle.dump([files,NsrcDic],f)

# with open('data_aux/cfgs_all_j','r') as f:
#     cfgs=f.read().splitlines()
# cfgs_all_j=cfgs

# jDic={}
# for i,cfg in enumerate(cfgs_all_j):
#     print(i+1,len(cfgs_all_j),end='               \r')
#     path=f'{basepath}{cfg}/j.h5'
#     with h5py.File(path) as f:
#         t=list(f['data'].keys()); t.sort()
#         jDic[cfg]=t
#     # break

# with open('data_aux/jDic.pkl','wb') as f:
#     pickle.dump(jDic,f)
# cfgs_all_j=cfgs

In [4]:
import os,pickle
import h5py
import numpy as np

with open('data_aux/NsrcDic.pkl','rb') as f:
    files,NsrcDic=pickle.load(f)
cfgs_all_N=list(NsrcDic.keys()); cfgs_all_N.sort()
cfgs=[]
for cfg in cfgs_all_N:
    if NsrcDic[cfg] != (200,85,64):
        # print(cfg, NsrcDic[cfg])
        continue
    # print(cfg, NsrcDic[cfg])
    cfgs.append(cfg)
with open('data_aux/cfgs_N=200,85,64','w') as f:
    f.write('\n'.join(cfgs))
cfgsN=cfgs
    
with open('data_aux/jDic.pkl','rb') as f:
    jDic=pickle.load(f)
cfgs_all_j=list(jDic.keys()); cfgs_all_j.sort()

with open('data_aux/cfgs_all_jg','r') as f:
    cfgs=f.read().splitlines()
cfgs_jg=cfgs

cfgs=[]
for cfg in cfgs_all_j:
    if 'j+' not in jDic[cfg]:
        # print(cfg,jDic[cfg])
        continue
    cfgs.append(cfg)
with open('data_aux/cfgs_jl','w') as f:
    f.write('\n'.join(cfgs))
cfgsj=cfgs

cfgs=list(set(cfgsN).intersection(cfgsj)); cfgs.sort()
print(len(cfgsN),len(cfgsj),len(cfgs))
with open('data_aux/cfgs_N=200,85,64_jl','w') as f:
    f.write('\n'.join(cfgs))

cfgs=[]
for cfg in cfgs_all_j:
    if len(jDic[cfg]) != 20:
        # print(cfg,jDic[cfg])
        continue
    cfgs.append(cfg)
with open('data_aux/cfgs_jlsc','w') as f:
    f.write('\n'.join(cfgs))
cfgsj=cfgs

cfgs=list(set(cfgsN).intersection(cfgsj)); cfgs.sort()
print(len(cfgsN),len(cfgsj),len(cfgs))
with open('data_aux/cfgs_N=200,85,64_jlsc','w') as f:
    f.write('\n'.join(cfgs))
    

cfgsj=set(cfgsj).intersection(cfgs_jg)
cfgs=list(set(cfgsN).intersection(cfgsj)); cfgs.sort()
print(len(cfgsN),len(cfgsj),len(cfgs))
with open('data_aux/cfgs_N=200,85,64_jlscg','w') as f:
    f.write('\n'.join(cfgs))

745 767 745
745 749 743
745 749 743


In [175]:
NB=26*743/1024
NC=37*400/1024
ND=48*494/1024
print(NB,NC,ND)
print(NB+NC+ND)

18.865234375 14.453125 23.15625
56.474609375


In [21]:
# Q2 range

import numpy as np 

enss=['b','c','d','e']
ens2full={'a24':'cA211.53.24','a':'cA2.09.48','b':'B64','c':'C80','d':'D96'}
ens2label={'a24':'A24','a':'A48','b':'B64','c':'C80','d':'D96'}
ens2a={'a24':0.0908,'a':0.0938,'b':0.07957,'c':0.06821,'d':0.05692,'e': 0.04892} # fm
ens2N={'a24':24,'a':48,'b':64,'c':80,'d':96, 'e':112}
ens2N_T={'a24':24*2,'a':48*2,'b':64*2,'c':80*2,'d':96*2,'e':112*2}

# ens2mN={'a':931}
# ens2mpiC={'a':131}
# ens2mpi0={'a':111}

ens2amu={'a24':0.0053,'a':0.0009,'b':0.00072}
ens2ZP={'a24':(0.4670,0.0046),'a':(0.500,0.030)}

hbarc = 1/197.3
ens2aInv={ens:1/(ens2a[ens]*hbarc) for ens in enss} # MeV

def getQ2(n2,ens):
    mN=0.938
    q2=(2*np.pi/(ens2N[ens])*ens2aInv[ens]/1000)**2 * n2
    EN=np.sqrt(mN**2+q2)
    Q2=q2 - (EN-mN)**2
    return Q2

enss=['b','c','d','e']
enss=['b','c','d']
for ens in enss:
    print(ens)
    for n2 in np.arange(30+1):
        Q2=getQ2(n2,ens)
        # if 0.9<Q2<1.1:
        #     print(n2,Q2)
        if 0.6<Q2<0.8:
            print(n2,Q2)

b
12 0.606567187945291
13 0.6502329034542685
14 0.693121390746389
15 0.7352727319077199
16 0.7767236779792155
c
14 0.615057263729054
15 0.652997583634813
16 0.6903504452810004
17 0.727142320152669
18 0.7633977494556757
19 0.7991395356072737
d
14 0.6135841644929141
15 0.65144406434549
16 0.6887186036246935
17 0.7254341220759091
18 0.761615041403221
19 0.7972840552925868


In [24]:
# jg mom
import numpy as np

for ens in enss:
    if ens=='b':
        path='/onyx/qdata/gspanoudes/Local_operators/Matrix_elements/cB64/data/gluon_loops_stout4D/stout0/cB64a/0500/gLoops_ultralocal_Clv_EMT_00_0500.dat'
    if ens=='c':
        path='/onyx/qdata/gspanoudes/Local_operators/Matrix_elements/cC80/data/gluon_loops_stout4D/stout0/cC80a/0500/gLoops_ultralocal_Clv_EMT_00_0500.dat'
    if ens=='d':
        path='/onyx/qdata/gspanoudes/Local_operators/Matrix_elements/cD96/data/gluon_loops_stout/stout0/cD96a/0000/gLoops_ultralocal_Clv_EMT_00_0000.dat'
    with open(path,'r') as f:
        t=f.read().split('\n')[:-1]
        tt=[row.split(' ') for row in t]
        N_tot=len(t)
        N_T=np.max([int(row[1]) for row in tt])+1
        N_mom=N_tot//N_T
        moms=[[int(ele) for ele in row[3:6]] for row in tt[:N_mom]]
        
        maxmom2=np.max([mom[0]**2+mom[1]**2+mom[2]**2 for mom in moms])
        
        print(ens,N_tot,N_T,N_mom,maxmom2,getQ2(maxmom2,ens))

b 32896 128 257 16 0.7767236779792155
c 41120 160 257 16 0.6903504452810004
d 589632 192 3071 81 2.455594211068091


In [9]:
import h5py
path='/p/project1/ngff/li47/code/projectData/02_discNJN_1D/cD211.054.96/data_post_hold/a0000/jg.h5'
with h5py.File(path) as f:
    print(f['moms'][:])

[[-2  0  0]
 [-1 -1 -1]
 [-1 -1  0]
 [-1 -1  1]
 [-1  0 -1]
 [-1  0  0]
 [-1  0  1]
 [-1  1 -1]
 [-1  1  0]
 [-1  1  1]
 [ 0 -2  0]
 [ 0 -1 -1]
 [ 0 -1  0]
 [ 0 -1  1]
 [ 0  0 -2]
 [ 0  0 -1]
 [ 0  0  0]
 [ 0  0  1]
 [ 0  0  2]
 [ 0  1 -1]
 [ 0  1  0]
 [ 0  1  1]
 [ 0  2  0]
 [ 1 -1 -1]
 [ 1 -1  0]
 [ 1 -1  1]
 [ 1  0 -1]
 [ 1  0  0]
 [ 1  0  1]
 [ 1  1 -1]
 [ 1  1  0]
 [ 1  1  1]
 [ 2  0  0]]


# check mark

In [67]:
import os
import h5py
import numpy as np

path='/p/project/ngff/li47/code/temp/EMT_cB64.h5'
path2='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post/a0500/j.h5'
path3='/p/project/ngff/li47/code/projectData/NST_f_discBCD/cB211.072.64/data_post/a0500/j.h5'
path4='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post_hold/a0500/j.h5'
with h5py.File(path) as f, h5py.File(path2) as f2, h5py.File(path3) as f3, h5py.File(path4) as f4:
    print(f['cB211a.072.64/light-lm+hp/0500'].keys())
    print(f['cB211a.072.64/light-hp2/0500'].keys())
    t=f['cB211a.072.64/light-hp2/0500/T01/Re'][:]+1j*f['cB211a.072.64/light-hp2/0500/T01/Im'][:]
    print(t[:2])
    t=f['cB211a.072.64/light-lm+hp/0500/T01/Re'][:]+1j*f['cB211a.072.64/light-lm+hp/0500/T01/Im'][:]
    print(t[:2])
    
    moms=[tuple(mom) for mom in f2['moms'][:]]
    i_mom=moms.index((0,0,0))
    # print(i_mom)
    # print(f2.keys())
    # print(f2['inserts;g{m,Dn};tl'][:])
    t=f2['data/j+;g{m,Dn};tl'][:2,i_mom,1]
    print(t)
    
    # moms=[tuple(mom) for mom in f3['moms'][:]]
    # i_mom=moms.index((0,0,0))
    # print(i_mom)
    # print(f3['data/j'][:2,i_mom,1])
    
    # print(f4['inserts'][:])
    # moms=[tuple(mom) for mom in f4['moms'][:]]
    # i_mom=moms.index((0,0,0))
    # t=(f4['data/j+;d3'][:2,i_mom,1]+f4['data/j+;d0'][:2,i_mom,4])/2
    # print(t)

<KeysViewHDF5 ['T01', 'T02', 'T03']>
<KeysViewHDF5 ['T01', 'T02', 'T03']>
[25.63203336+5.88499399j  7.30661551-4.64111744j]
[29.41624123+1.08716248j  5.57684572+0.68357665j]
[29.41624123+1.08716248j  5.57684572+0.68357665j]


In [151]:
import os
import h5py
import numpy as np

path='/p/project/ngff/li47/code/temp/Yan_c3pts.h5'
path2='/p/project/ngff/li47/code/scratch/run/02_discNJN_1D/cB211.072.64/data_avgsrc/a0500/discNJN_j+;g{m,Dn};tl.h5'
with h5py.File(path) as f, h5py.File(path2) as f2:
    print(f['cB64a/light-lm+hp/0500_r0/pix0piy0piz1/fwd'].keys())
    
    t=f['cB64a/light-lm+hp/0500_r0/pix0piy0piz1/fwd/8']
    print(t[:])
    t=f['cB64a/light-lm+hp/0500_r0/pix1piy0piz0/fwd/8']
    print(t[:])
    t=f['cB64a/light-lm+hp/0500_r0/pix0piy-1piz0/fwd/8']
    print(t[:])
    
    moms=[tuple(mom) for mom in f2['moms'][:]]
    print(f2['notes'][:])
    i_mom=moms.index((0,0,1,0,0,0))
    print(f2['inserts;g{m,Dn};tl'][:])
    t=f2['data/N_N_j+;g{m,Dn};tl_8'][:2,i_mom,0,3]
    print(t)
    

<KeysViewHDF5 ['10', '12', '14', '16', '18', '20', '6', '8']>
[-9.41641703e-10 -1.70565620e-10  6.52621819e-10  6.60912107e-11
  1.31048697e-10  4.77494436e-10 -5.89194488e-10 -8.30247921e-10
 -5.24081074e-10]
[ 4.90679093e-10  9.54086258e-10  1.11496614e-09 -3.77210912e-11
  6.40517761e-11 -2.05529999e-11  5.50904322e-10 -3.39178904e-10
 -1.12145923e-09]
[ 1.04658463e-09  6.33919624e-11 -3.13179155e-10  2.64650339e-10
 -2.05381693e-10  3.72768335e-10  4.23453159e-10 -8.25611597e-10
 -1.30535595e-09]
[b'time,mom,proj,insert' b'mom=[sink,ins]; sink+ins=src'
 b'proj=[P0,Px,Py,Pz]']
[b'tt' b'tx' b'ty' b'tz' b'xx' b'xy' b'xz' b'yy' b'yz' b'zz']
[1.32812801e-09-4.94128917e-10j 2.65562887e-10-1.22013427e-10j]


In [156]:
import re
lat_L=64

def src2ints(src):
    (sx,sy,sz,st)=re.search('sx([0-9]*)sy([0-9]*)sz([0-9]*)st([0-9]*)',src).groups()
    (sx,sy,sz,st)=(int(sx),int(sy),int(sz),int(st))
    return (sx,sy,sz,st)
def get_phase(src_int,mom):
    (sx,sy,sz,st)=src_int
    return np.exp(1j*(2*np.pi/lat_L)*(np.array([sx,sy,sz])@mom))

tf=8

path='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post/a0500/'
with h5py.File(f'{path}j.h5') as fj, h5py.File(f'{path}N.h5_hch02k_twop') as f1, h5py.File(f'{path}N.h5_twop_threep_2') as f2, h5py.File(f'{path}N.h5_twop_threep_dt20_64srcs') as f3:
    moms=[tuple(mom) for mom in fj['moms']]
    i_mom=moms.index((0,0,0))
    print(fj['inserts;g5g{m,Dn};tl'][:])
    tj=fj['data/j+;g{m,Dn};tl'][:,i_mom,2]
    
    moms=[tuple(mom) for mom in f1['moms']]
    i_mom=moms.index((0,-1,0))
    tres=[]
    for f in [f1,f2,f3][:1]:
        for src in f['data'].keys():
            src_int=src2ints(src)
            t=f[f'data/{src}/N_N'][tf,i_mom,0]
            tj_temp=np.roll(tj,-src_int[-1])[:tf+1]
            # tres.append(t*tj_temp)
            tres.append(np.imag(t)*np.real(tj_temp))
            # tres.append(np.real(t)*np.imag(tj_temp))
            # break
        # break
    print(len(tres))
    t=np.mean(tres,axis=0)*2
    print(t)


[b'tt' b'tx' b'ty' b'tz' b'xx' b'xy' b'xz' b'yy' b'yz' b'zz']
200
[ 1.04658461e-09  6.33919620e-11 -3.13179168e-10  2.64650311e-10
 -2.05381701e-10  3.72768339e-10  4.23453157e-10 -8.25611594e-10
 -1.30535597e-09]


# old checks

In [169]:
ens=['cB211.072.64','cC211.060.80','cD211.054.96'][2]
cfg={'cB211.072.64':'a0500','cC211.060.80':'a0500','cD211.054.96':'a0000'}[ens]

path1=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/{ens}/data_avgsrc_check/{cfg}/N.h5'
path2=f'/p/project/ngff/li47/code/temp/{ens}/{cfg}/N.h5'
path3=f'/p/project/ngff/li47/code/temp/{ens}/{cfg}/N_bw.h5'
with h5py.File(path1) as f1, h5py.File(path2) as f2, h5py.File(path3) as f3:
    moms1=[list(mom) for mom in f1['moms']]
    
    t1=f1['data/N_N'][:36,moms1.index([0,-1,0])]
    print(f2['opabs'][[2,3]])
    t2=(f2['data/N1_N1'][:]+f2['data/N2_N2'])/2
    t2=(t2[:,2]+t2[:,3])/2
    t2=t2[:36]
    print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
    
    t1=f1['data_bw/N_N'][1:36,moms1.index([0,1,0])]
    # print(f2['opabs'][[2,3]])
    t2=(f3['data/N1_N1'][:]+f3['data/N2_N2'])/2
    t2=(t2[:,2]+t2[:,3])/2
    t2=-np.flip(t2[1:])
    t2=t2[:35]
    print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
    
id=np.eye(4)
gamma_1=gamma_x=np.array([[0.,0.,0.,1j],[0.,0.,1j,0.],[0.,-1j,0.,0.],[-1j,0.,0.,0.]])
gamma_2=gamma_y=np.array([[0.,0.,0.,1.],[0.,0.,-1.,0.],[0.,-1.,0.,0.],[1.,0.,0.,0.]])
gamma_3=gamma_z=np.array([[0.,0.,1j,0.],[0.,0.,0.,-1j],[-1j,0.,0.,0.],[0.,1j,0.,0.]])
gamma_4=gamma_t=np.array([[1.,0.,0.,0.],[0.,1.,0.,0.],[0.,0.,-1.,0.],[0.,0.,0.,-1.]])
gamma_5=(gamma_1@gamma_2@gamma_3@gamma_4)
#
P0=(id+gamma_4)/4; Px=1j*gamma_5@gamma_1@P0; Py=1j*gamma_5@gamma_2@P0; Pz=1j*gamma_5@gamma_3@P0
P0n=(id-gamma_4)/4; Pxn=1j*gamma_5@gamma_1@P0n; Pyn=1j*gamma_5@gamma_2@P0n; Pzn=1j*gamma_5@gamma_3@P0n
#
# coeff_{i} C_{i=4a+b} = Tr[proj@C] = proj_{ba} C_{ab} = proj_{ba} C_{4a+b} 
# coeff_{i=4a+b} = proj_{ba}
dirac2proj=np.array([[complex(ele) for row in proj.T for ele in row] for proj in [P0,Px,Py,Pz]])[:,[0,1,4,5]]
dirac2proj_bw=np.array([[complex(ele) for row in proj.T for ele in row] for proj in [P0n,Pxn,Pyn,Pzn]])[:,[10,11,14,15]]

for j in ['j+','j-','js','jc']:
    print()
    path1=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/{ens}/data_avgsrc_check/{cfg}/discNJN_{j}.h5'
    path2=f'/p/project/ngff/li47/code/temp/{ens}/{cfg}/N-j.h5'
    path3=f'/p/project/ngff/li47/code/temp/{ens}/{cfg}/N_bw-j.h5'
    with h5py.File(path1) as f1, h5py.File(path2) as f2, h5py.File(path3) as f3:
        moms1=[list(mom) for mom in f1['moms']]

        t1=f1[f'data/N_N_{j}_13'][:,moms1.index([0,0,1,0,0,0]),:,:]
        opabs=[opab.decode() for opab in f2['opabs']]
        inds=[opabs.index('g;0,0,1;G1;a;l1;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,1;G1;a;l1;N_g;0,0,1;G1;a;l2;N'),opabs.index('g;0,0,1;G1;a;l2;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,1;G1;a;l2;N_g;0,0,1;G1;a;l2;N')]
        # print(f2['opabs'][inds])
        t2=(f2[f'data/N1_{j}_N1_deltat_13'][:]+f2[f'data/N2_{j}_N2_deltat_13'][:])/2
        t2=t2[:,inds]
        t2=np.einsum('pd,tdj->tpj',dirac2proj,t2)
        print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
        
        t1=f1[f'data_bw/N_N_{j}_13'][:,moms1.index([0,0,-1,0,0,0]),:,0]
        opabs=[opab.decode() for opab in f2['opabs']]
        inds=[opabs.index('g;0,0,1;G1;a;l1;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,1;G1;a;l1;N_g;0,0,1;G1;a;l2;N'),opabs.index('g;0,0,1;G1;a;l2;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,1;G1;a;l2;N_g;0,0,1;G1;a;l2;N')]
        # print(f2['opabs'][inds])
        t2=(f3[f'data/N1_{j}_N1_deltat_13'][:]+f3[f'data/N2_{j}_N2_deltat_13'][:])/2
        t2=t2[:,inds]
        t2=np.einsum('pd,tdj->tpj',dirac2proj,t2)
        t2=-t2[:,:,0]
        t2[:,1:]*=-1
        print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
        
        
        t1=f1[f'data/N_N_{j}_13'][:,moms1.index([0,0,0,0,0,1]),:,:]
        opabs=[opab.decode() for opab in f2['opabs']]
        inds=[opabs.index('g;0,0,0;G1g;a;l1;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,0;G1g;a;l1;N_g;0,0,1;G1;a;l2;N'),opabs.index('g;0,0,0;G1g;a;l2;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,0;G1g;a;l2;N_g;0,0,1;G1;a;l2;N')]
        # print(f2['opabs'][inds])
        t2=(f2[f'data/N1_{j}_N1_deltat_13'][:]+f2[f'data/N2_{j}_N2_deltat_13'][:])/2
        t2=t2[:,inds]
        t2=np.einsum('pd,tdj->tpj',dirac2proj,t2)
        print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
        
        t1=f1[f'data_bw/N_N_{j}_13'][:,moms1.index([0,0,0,0,0,-1]),:,0]
        opabs=[opab.decode() for opab in f2['opabs']]
        inds=[opabs.index('g;0,0,0;G1g;a;l1;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,0;G1g;a;l1;N_g;0,0,1;G1;a;l2;N'),opabs.index('g;0,0,0;G1g;a;l2;N_g;0,0,1;G1;a;l1;N'),opabs.index('g;0,0,0;G1g;a;l2;N_g;0,0,1;G1;a;l2;N')]
        # print(f2['opabs'][inds])
        t2=(f3[f'data/N1_{j}_N1_deltat_13'][:]+f3[f'data/N2_{j}_N2_deltat_13'][:])/2
        t2=t2[:,inds]
        t2=np.einsum('pd,tdj->tpj',dirac2proj,t2)
        t2=-t2[:,:,0]
        t2[:,1:]*=-1
        print(np.max(np.abs(t1-t2)),np.mean(np.abs(t1)))
    # break

[b'g;0,-1,0;G1;a;l1;N_g;0,-1,0;G1;a;l1;N'
 b'g;0,-1,0;G1;a;l2;N_g;0,-1,0;G1;a;l2;N']
1.1102278e-16 5.724313e-11
1.3021715e-18 1.2284886e-12

4.4820276343997245e-17 6.230908971293657e-10
1.12334261397781e-16 1.0351851340344961e-08
3.150244512461011e-18 1.5149724200342756e-11
1.426593305205572e-18 3.100875109440553e-11

6.988838204538545e-14 9.33599074764877e-07
3.711192011551114e-18 6.386881105920897e-11
9.128194180625275e-18 2.0489902706221643e-11
3.6427991290175286e-18 5.136064769342013e-11

2.942159017931425e-16 3.934297801397967e-09
7.178677046565082e-16 6.771248431544101e-08
1.4890232461692739e-18 5.4836835125086e-12
6.825396085327536e-19 1.1329483724647031e-11

3.174910128534638e-15 4.240476084083598e-08
7.744996414760564e-15 7.310157929568454e-07
1.1294331780678725e-18 5.91206878222174e-12
1.416152156409167e-18 1.455498133029926e-11


In [ ]:
# import os
# import h5py
# import numpy as np

# path='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post/a0500/j.h5'
# path2='/p/project/ngff/li47/code/projectData/NST_f_discBCD/cB211.072.64/data_post/a0500/j.h5'
# with h5py.File(path) as f1, h5py.File(path2) as f2:
#     m1=f1['moms'][:]
#     m2=f2['moms'][:]
#     # m1=[list(ele) for ele in m1]
#     # m2=[list(ele) for ele in m2]
#     # m1.sort()
#     # m2.sort()
#     # print(np.all(m1==m2))
    
#     dic1={}
#     for i,mom in enumerate(m1):
#         dic1[tuple(mom)]=i
#     dic2={}
#     for i,mom in enumerate(m2):
#         dic2[tuple(mom)]=i
    
#     mom=(0,0,1)
    
#     t1=f1['data/j+_g{m,Dn}_tl'][:,dic1[mom],:]

#     t2=f2['data/j'][:,dic2[mom],:]
#     print(np.max(np.abs(t1-t2)))
    


1.0805156823142814e-14


In [103]:
import os
import h5py
import numpy as np

# path1='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post/a0500/j_1.h5'
# path2='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post/a0500/j_2.h5'
# with h5py.File(path1) as f1,h5py.File(path2) as f2:
#     print(f1['data'].keys())
#     t1=f1['data/j+_SGM[m{n],Dr}_tl'][:]
#     t2=f2['data/j+_SGM[m{n],Dr}_tl'][:]
#     print(np.abs(t1-t2))

# path1='/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_avgsrc/a0500/N-j.h5'
# path2='/p/project/ngff/li47/code/projectData/NST_f_discBCD/cB211.072.64/data_avgsrc/a0500/N-j.h5'
# with h5py.File(path1) as f1, h5py.File(path2) as f2:
#     print(f1['data'].keys())
#     print(f2['data'].keys())
    
#     ky1='N_N_j+_g{m,Dn}_tl_11'
#     ky2='N_N_j_11'
#     t1=f1[f'data/{ky1}'][:]
#     t2=f2[f'data/{ky2}'][:]
#     print(np.max(np.abs(t1-t2)))
    
#     ky1='N_N_j+_g{m,Dn}_tl_11'
#     ky2='N_N_j_11'
#     t1=f1[f'data_bw/{ky1}'][:]
#     t2=f2[f'data_bw/{ky2}'][:]
#     print(np.max(np.abs(t1-t2)))

# file='N.h5_hch02k_twop'
# file='N.h5_twop_threep_2'
# file='N.h5_twop_threep_dt20_64srcs'
# path1=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_post_hold/a0500/{file}'
# path2=f'/p/project/ngff/li47/code/projectData/02_discNJN_1D/cB211.072.64/data_N_fullmom/a0500/{file}'
# with h5py.File(path1) as f1, h5py.File(path2) as f2:
    
#     fla='N1_N1'; dat='data'
    
#     moms1=[list(mom) for mom in f1['moms']]
#     moms2=[list(mom) for mom in f2['moms']]
#     momMap=[moms2.index(mom) for mom in moms1]
#     srcs=list(f1[dat].keys())
#     t1=0
#     for src in srcs:
#         t1+=f1[f'{dat}/{src}/{fla}'][:,:,[0,3]]
#     t1/=len(srcs)
    
#     t2=f2[f'{dat}/{fla}'][:]
#     t2=t2[:,momMap]
    
#     print(t1.shape)
#     print(np.max(np.abs((t1-t2)/t1)))
#     print(np.max(np.abs(t1-t2)))
    

(37, 33, 2)
0.0
0.0
