In [1]:
%load_ext autoreload
%autoreload 2

import util as yu
from util import *

yu.setpath('analysis_avgx')

projs=['P0', 'Px', 'Py', 'Pz']
inserts=['tt', 'tx', 'ty', 'tz', 'xx', 'xy', 'xz', 'yy', 'yz', 'zz']
enss=['b','c','d']

In [27]:
for ens in enss:
    cfg={'b':'a0500','c':'a0500','d':'a0000'}[ens]
    path=f'/p/project1/ngff/li47/code/projectData/02_discNJN_1D/{yu.ens2full[ens]}/data_post_hold/{cfg}/jg.h5'
    with h5py.File(path) as f:
        moms=f['moms'][:]
        dic=yu.moms2dic(moms)
        inserts=yu.decodeList(f['inserts'])
        t=f['data/jg;stout10'][:,dic[(0,0,0)],inserts.index('tz')]
        factor=1/(1j*2*np.pi/yu.ens2NL[ens])
        t=np.real(t*factor)
        print(t[:4])

[2.66458317e-15 1.60588287e-15 2.62306531e-16 4.76715034e-16]
[ 2.09872708e-15 -1.90116379e-16 -2.01659668e-15 -1.34368439e-15]
[-1.22148556e-15  1.65795284e-15  2.64255150e-15 -1.40457952e-15]
